Dlp
prodmgmtprog/Product-Management-Curriculum pull request #43
Opened 2020-10-29 15:18 UTC by bethanyios

Still need to do reflections

2020-11-05 11:15 UTC, jc2820 commented on case-studies/DLP.md
> +* What makes sense to us, doesn't always to participants. We encourage usability testing of all prototypes and products in order to understand how people unfamiliar interact with what we've created.
```suggestion
* What makes sense to us, doesn't always to participants. We encourage usability testing of all prototypes and products in order to understand how people unfamiliar interact with what we've created. In the same way, we must consider the understanding of exercises we're familiar with as not obviously intuitive to participants. Explaining things in concise terms without jargon and with patience is key to success.
```

2020-11-05 11:25 UTC, jc2820 commented on case-studies/DLP.md
> +* Solutions should fit to what users use already - if users don't use apps, don't build an app; if they use Facebook, use Facebook.
```suggestion
* Solutions needn't always come in the form of a bespoke app. For example, if the current service uses Facebook, and users are shown to be happy with that format, find a solution that still uses Facebook, but improves the service in areas where it is lacking. 
```

2020-11-05 11:26 UTC, jc2820 requested changes
Just a couple of typos and a suggestion for one point that could perhaps be defined a little better.

2020-11-06 11:25 UTC, Albadylic approved these changes
One small change, otherwise happy for this to merge - if you're happy with reflections, @bethanyios

2020-11-06 11:25 UTC, Albadylic commented on case-studies/DLP.md
> +Moving forward from the programme, the organisations had three directions they could go in the next phase with CAST. Continuing with user research and discovery, using off-the-shelf solutions or a be
```suggestion
Moving forward from the programme, the organisations had three directions they could go in the next phase with Catalyst and The National Lottery Community Fund. Continuing with user research and discovery, using off-the-shelf solutions or a bespoke development - each organisation was guided towards being a position to follow one of these options based on what they had discovered about their problem area and user groups. They were also given the skillset and tools to be able to communicate about digital service design for other funding applications, having learnt the right language and understanding the process of development.
```

2020-11-06 14:11 UTC, Albadylic commented on case-studies/DLP.md
> +* Trust in the process is a key factor in reaching the goal. We've found that participants who second guess or hestitate to engage get less out of programmes than those who jump straight in with enth
```suggestion
* Trust in the process is a key factor in reaching the goal. We've found that participants who second guess or hesitate to engage get less out of programmes than those who jump straight in with enthusiasm, even without knowing the destination. 
```

2020-11-13 11:46 UTC, Albadylic approved these changes

2020-11-13 11:46 UTC, merged